apiVersion: retro.sparkfabrik.com/v1
kind: Game
metadata:
  name: tetris
  namespace: games
spec:
  name: "Tetris"
  zipUrl: "https://dosgames.com/files/f-tetris.zip"
  dir: "."
  exe: "F-TETRIS.EXE"
